export const errors = [
    {
        type: "error",
        name: "AllowanceExpired",
        inputs: [{ name: "deadline", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "ExcessiveInvalidation", inputs: [] },
    {
        type: "error",
        name: "InsufficientAllowance",
        inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "InvalidAmount", inputs: [{ name: "maxAmount", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "LengthMismatch", inputs: [] },
    {
        type: "error",
        name: "AlreadySubscribed",
        inputs: [
            { name: "tokenId", type: "uint256", internalType: "uint256" },
            { name: "subscriber", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "BurnNotificationReverted",
        inputs: [
            { name: "subscriber", type: "address", internalType: "address" },
            { name: "reason", type: "bytes", internalType: "bytes" },
        ],
    },
    { type: "error", name: "DeadlinePassed", inputs: [{ name: "deadline", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "GasLimitTooLow", inputs: [] },
    {
        type: "error",
        name: "ModifyLiquidityNotificationReverted",
        inputs: [
            { name: "subscriber", type: "address", internalType: "address" },
            { name: "reason", type: "bytes", internalType: "bytes" },
        ],
    },
    { type: "error", name: "NoCodeSubscriber", inputs: [] },
    { type: "error", name: "NoSelfPermit", inputs: [] },
    { type: "error", name: "NonceAlreadyUsed", inputs: [] },
    { type: "error", name: "NotApproved", inputs: [{ name: "caller", type: "address", internalType: "address" }] },
    { type: "error", name: "NotSubscribed", inputs: [] },
    { type: "error", name: "PoolManagerMustBeLocked", inputs: [] },
    { type: "error", name: "SignatureDeadlineExpired", inputs: [] },
    {
        type: "error",
        name: "SubscriptionReverted",
        inputs: [
            { name: "subscriber", type: "address", internalType: "address" },
            { name: "reason", type: "bytes", internalType: "bytes" },
        ],
    },
    { type: "error", name: "Unauthorized", inputs: [] },
    { type: "error", name: "AlreadyUnlocked", inputs: [] },
    {
        type: "error",
        name: "CurrenciesOutOfOrderOrEqual",
        inputs: [
            { name: "currency0", type: "address", internalType: "address" },
            { name: "currency1", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "CurrencyNotSettled", inputs: [] },
    { type: "error", name: "InvalidCaller", inputs: [] },
    { type: "error", name: "ManagerLocked", inputs: [] },
    { type: "error", name: "MustClearExactPositiveDelta", inputs: [] },
    { type: "error", name: "NonzeroNativeValue", inputs: [] },
    { type: "error", name: "PoolNotInitialized", inputs: [] },
    { type: "error", name: "ProtocolFeeCurrencySynced", inputs: [] },
    { type: "error", name: "ProtocolFeeTooLarge", inputs: [{ name: "fee", type: "uint24", internalType: "uint24" }] },
    { type: "error", name: "SwapAmountCannotBeZero", inputs: [] },
    {
        type: "error",
        name: "TickSpacingTooLarge",
        inputs: [{ name: "tickSpacing", type: "int24", internalType: "int24" }],
    },
    {
        type: "error",
        name: "TickSpacingTooSmall",
        inputs: [{ name: "tickSpacing", type: "int24", internalType: "int24" }],
    },
    { type: "error", name: "UnauthorizedDynamicLPFeeUpdate", inputs: [] },
    { type: "error", name: "DelegateCallNotAllowed", inputs: [] },
    { type: "error", name: "ContractLocked", inputs: [] },
    {
        type: "error",
        name: "DeltaNotNegative",
        inputs: [{ name: "currency", type: "address", internalType: "Currency" }],
    },
    {
        type: "error",
        name: "DeltaNotPositive",
        inputs: [{ name: "currency", type: "address", internalType: "Currency" }],
    },
    { type: "error", name: "InputLengthMismatch", inputs: [] },
    { type: "error", name: "InsufficientBalance", inputs: [] },
    { type: "error", name: "InvalidContractSignature", inputs: [] },
    { type: "error", name: "InvalidEthSender", inputs: [] },
    { type: "error", name: "InvalidSignature", inputs: [] },
    { type: "error", name: "InvalidSignatureLength", inputs: [] },
    { type: "error", name: "InvalidSigner", inputs: [] },
    {
        type: "error",
        name: "MaximumAmountExceeded",
        inputs: [
            { name: "maximumAmount", type: "uint128", internalType: "uint128" },
            { name: "amountRequested", type: "uint128", internalType: "uint128" },
        ],
    },
    {
        type: "error",
        name: "MinimumAmountInsufficient",
        inputs: [
            { name: "minimumAmount", type: "uint128", internalType: "uint128" },
            { name: "amountReceived", type: "uint128", internalType: "uint128" },
        ],
    },
    { type: "error", name: "NotPoolManager", inputs: [] },
    {
        type: "error",
        name: "UnsupportedAction",
        inputs: [{ name: "action", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "NotEnoughLiquidity",
        inputs: [{ name: "poolId", type: "bytes32", internalType: "PoolId" }],
    },
    { type: "error", name: "NotSelf", inputs: [] },
    { type: "error", name: "QuoteSwap", inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "UnexpectedCallSuccess", inputs: [] },
    {
        type: "error",
        name: "UnexpectedRevertBytes",
        inputs: [{ name: "revertData", type: "bytes", internalType: "bytes" }],
    },
    { type: "error", name: "UnsupportedProtocolError", inputs: [] },
    { type: "error", name: "ETHNotAccepted", inputs: [] },
    {
        type: "error",
        name: "ExecutionFailed",
        inputs: [
            { name: "commandIndex", type: "uint256", internalType: "uint256" },
            { name: "message", type: "bytes", internalType: "bytes" },
        ],
    },
    { type: "error", name: "TransactionDeadlinePassed", inputs: [] },
    { type: "error", name: "BalanceTooLow", inputs: [] },
    { type: "error", name: "CallTargetPermit2", inputs: [] },
    { type: "error", name: "FromAddressIsNotOwner", inputs: [] },
    { type: "error", name: "InsufficientETH", inputs: [] },
    { type: "error", name: "InsufficientToken", inputs: [] },
    { type: "error", name: "InvalidAction", inputs: [{ name: "action", type: "bytes4", internalType: "bytes4" }] },
    { type: "error", name: "InvalidBips", inputs: [] },
    {
        type: "error",
        name: "InvalidCommandType",
        inputs: [{ name: "commandType", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "InvalidPath", inputs: [] },
    { type: "error", name: "InvalidReserves", inputs: [] },
    {
        type: "error",
        name: "NotAuthorizedForToken",
        inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "OnlyMintAllowed", inputs: [] },
    { type: "error", name: "SliceOutOfBounds", inputs: [] },
    { type: "error", name: "UnsafeCast", inputs: [] },
    { type: "error", name: "V2InvalidPath", inputs: [] },
    { type: "error", name: "V2TooLittleReceived", inputs: [] },
    { type: "error", name: "V2TooMuchRequested", inputs: [] },
    { type: "error", name: "V3InvalidAmountOut", inputs: [] },
    { type: "error", name: "V3InvalidCaller", inputs: [] },
    { type: "error", name: "V3InvalidSwap", inputs: [] },
    { type: "error", name: "V3TooLittleReceived", inputs: [] },
    { type: "error", name: "V3TooMuchRequested", inputs: [] },
    {
        type: "error",
        name: "V4TooLittleReceived",
        inputs: [
            { name: "minAmountOutReceived", type: "uint256", internalType: "uint256" },
            { name: "amountReceived", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "V4TooMuchRequested",
        inputs: [
            { name: "maxAmountInRequested", type: "uint256", internalType: "uint256" },
            { name: "amountRequested", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "InvalidCallbackAddress",
        inputs: [
            { name: "msgSender", type: "address", internalType: "address" },
            { name: "expectedPoolAddress", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "PoolDoesNotExist", inputs: [{ name: "pool", type: "address", internalType: "address" }] },
    { type: "error", name: "V2PoolDoesNotExist", inputs: [{ name: "pool", type: "address", internalType: "address" }] },
    { type: "error", name: "ContractUnlocked", inputs: [] },
    { type: "error", name: "NegativeBalanceDelta", inputs: [] },
    { type: "error", name: "TargetIsHook", inputs: [] },
    { type: "error", name: "TargetIsISM", inputs: [] },
    { type: "error", name: "TargetIsMailbox", inputs: [] },
    { type: "error", name: "BalanceZero", inputs: [] },
    {
        type: "error",
        name: "AccountDeploymentFailed",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "InvalidExecutorMode", inputs: [] },
    {
        type: "error",
        name: "InvalidRemoteRouterOwner",
        inputs: [
            { name: "account", type: "address", internalType: "address" },
            { name: "domain", type: "uint32", internalType: "uint32" },
            { name: "router", type: "address", internalType: "address" },
            { name: "owner", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "InvalidTimestamp",
        inputs: [
            { name: "validUntil", type: "uint48", internalType: "uint48" },
            { name: "validAfter", type: "uint48", internalType: "uint48" },
        ],
    },
    { type: "error", name: "EventPayloadNotSentMessage", inputs: [] },
    { type: "error", name: "IdOriginNotL2ToL2CrossDomainMessenger", inputs: [] },
    { type: "error", name: "InvalidChainId", inputs: [] },
    { type: "error", name: "MessageAlreadyRelayed", inputs: [] },
    { type: "error", name: "MessageDestinationNotRelayChain", inputs: [] },
    { type: "error", name: "MessageDestinationSameChain", inputs: [] },
    { type: "error", name: "MessageTargetCrossL2Inbox", inputs: [] },
    { type: "error", name: "MessageTargetL2ToL2CrossDomainMessenger", inputs: [] },
    { type: "error", name: "NotEntered", inputs: [] },
    { type: "error", name: "ReentrantCall", inputs: [] },
    { type: "error", name: "TargetCallFailed", inputs: [] },
    { type: "error", name: "InvalidCrossDomainSender", inputs: [] },
    { type: "error", name: "InvalidERC7802", inputs: [] },
    { type: "error", name: "ZeroAddress", inputs: [] },
    { type: "error", name: "AllowanceOverflow", inputs: [] },
    { type: "error", name: "AllowanceUnderflow", inputs: [] },
    { type: "error", name: "InsufficientAllowance", inputs: [] },
    { type: "error", name: "InvalidPermit", inputs: [] },
    { type: "error", name: "Permit2AllowanceIsFixedAtInfinity", inputs: [] },
    { type: "error", name: "PermitExpired", inputs: [] },
    { type: "error", name: "TotalSupplyOverflow", inputs: [] },
    {
        type: "error",
        name: "InvalidRemoteRouterOwner",
        inputs: [
            { name: "account", type: "address", internalType: "address" },
            { name: "domain", type: "uint256", internalType: "uint256" },
            { name: "owner", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "QuoteAmountTooLow", inputs: [] },
    { type: "error", name: "TransferFailed", inputs: [] },
    { type: "error", name: "EnableNotApproved", inputs: [] },
    { type: "error", name: "ExecutionReverted", inputs: [] },
    { type: "error", name: "InitConfigError", inputs: [{ name: "idx", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "InvalidCallType", inputs: [] },
    { type: "error", name: "InvalidExecutor", inputs: [] },
    { type: "error", name: "InvalidFallback", inputs: [] },
    { type: "error", name: "InvalidMode", inputs: [] },
    { type: "error", name: "InvalidModuleType", inputs: [] },
    { type: "error", name: "InvalidNonce", inputs: [] },
    { type: "error", name: "InvalidSelector", inputs: [] },
    { type: "error", name: "InvalidValidationType", inputs: [] },
    { type: "error", name: "InvalidValidator", inputs: [] },
    { type: "error", name: "NonceInvalidationError", inputs: [] },
    { type: "error", name: "NotSupportedCallType", inputs: [] },
    { type: "error", name: "OnlyExecuteUserOp", inputs: [] },
    { type: "error", name: "PermissionDataLengthMismatch", inputs: [] },
    { type: "error", name: "PermissionNotAlllowedForSignature", inputs: [] },
    { type: "error", name: "PermissionNotAlllowedForUserOp", inputs: [] },
    { type: "error", name: "PolicyDataTooLarge", inputs: [] },
    { type: "error", name: "PolicyFailed", inputs: [{ name: "i", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "PolicySignatureOrderError", inputs: [] },
    { type: "error", name: "RootValidatorCannotBeRemoved", inputs: [] },
    { type: "error", name: "SignerPrefixNotPresent", inputs: [] },
    { type: "error", name: "InitializeError", inputs: [] },
    {
        type: "error",
        name: "AlreadyInitialized",
        inputs: [{ name: "smartAccount", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "InvalidTargetAddress",
        inputs: [{ name: "target", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "NotInitialized",
        inputs: [{ name: "smartAccount", type: "address", internalType: "address" }],
    },
    { type: "error", name: "InvalidNonce", inputs: [{ name: "nonce", type: "uint256", internalType: "uint256" }] },
    { type: "error", name: "InvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
    { type: "error", name: "LinkedList_AlreadyInitialized", inputs: [] },
    {
        type: "error",
        name: "LinkedList_EntryAlreadyInList",
        inputs: [{ name: "entry", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "LinkedList_InvalidEntry",
        inputs: [{ name: "entry", type: "address", internalType: "address" }],
    },
    { type: "error", name: "LinkedList_InvalidPage", inputs: [] },
    { type: "error", name: "UnauthorizedAccess", inputs: [] },
    {
        type: "error",
        name: "DelegateAndRevert",
        inputs: [
            { name: "success", type: "bool", internalType: "bool" },
            { name: "ret", type: "bytes", internalType: "bytes" },
        ],
    },
    {
        type: "error",
        name: "FailedOp",
        inputs: [
            { name: "opIndex", type: "uint256", internalType: "uint256" },
            { name: "reason", type: "string", internalType: "string" },
        ],
    },
    {
        type: "error",
        name: "FailedOpWithRevert",
        inputs: [
            { name: "opIndex", type: "uint256", internalType: "uint256" },
            { name: "reason", type: "string", internalType: "string" },
            { name: "inner", type: "bytes", internalType: "bytes" },
        ],
    },
    { type: "error", name: "PostOpReverted", inputs: [{ name: "returnData", type: "bytes", internalType: "bytes" }] },
    {
        type: "error",
        name: "SenderAddressResult",
        inputs: [{ name: "sender", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "SignatureValidationFailed",
        inputs: [{ name: "aggregator", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
        type: "error",
        name: "OwnableInvalidOwner",
        inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "OwnableUnauthorizedAccount",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "BalanceNotReimbursed",
        inputs: [
            { name: "sender", type: "address", internalType: "address" },
            { name: "nonce", type: "uint256", internalType: "uint256" },
            { name: "reimbursed", type: "uint256", internalType: "uint256" },
            { name: "actualGasCost", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "RefundFailed",
        inputs: [
            { name: "sender", type: "address", internalType: "address" },
            { name: "nonce", type: "uint256", internalType: "uint256" },
            { name: "surplus", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "AmountTooLarge",
        inputs: [
            { name: "amount", type: "uint256", internalType: "uint256" },
            { name: "max", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "ERC20InsufficientAllowance",
        inputs: [
            { name: "spender", type: "address", internalType: "address" },
            { name: "allowance", type: "uint256", internalType: "uint256" },
            { name: "needed", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "ERC20InsufficientBalance",
        inputs: [
            { name: "sender", type: "address", internalType: "address" },
            { name: "balance", type: "uint256", internalType: "uint256" },
            { name: "needed", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "ERC20InvalidApprover",
        inputs: [{ name: "approver", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "ERC20InvalidReceiver",
        inputs: [{ name: "receiver", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "ERC20InvalidSender",
        inputs: [{ name: "sender", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "ERC20InvalidSpender",
        inputs: [{ name: "spender", type: "address", internalType: "address" }],
    },
    { type: "error", name: "EmptyBasket", inputs: [] },
    { type: "error", name: "FailedCall", inputs: [] },
    {
        type: "error",
        name: "IncorrectETH",
        inputs: [
            { name: "actual", type: "uint256", internalType: "uint256" },
            { name: "expected", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "InsufficientBalance",
        inputs: [
            { name: "balance", type: "uint256", internalType: "uint256" },
            { name: "needed", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
    { type: "error", name: "UnsortedDuplicate", inputs: [{ name: "token", type: "address", internalType: "address" }] },
    { type: "error", name: "ZeroAmount", inputs: [] },
    { type: "error", name: "ZeroUnits", inputs: [] },
    { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
    { type: "error", name: "CallSelectorApprove", inputs: [] },
    { type: "error", name: "InvalidLocalDecimals", inputs: [] },
    {
        type: "error",
        name: "SlippageExceeded",
        inputs: [
            { name: "amountLD", type: "uint256", internalType: "uint256" },
            { name: "minAmountLD", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "AdapterParamsMustBeEmpty", inputs: [] },
    { type: "error", name: "AdditionToPoolIsBelowPerTransactionMinimum", inputs: [] },
    { type: "error", name: "AdditionToPoolWouldExceedPerAddressCap", inputs: [] },
    { type: "error", name: "AdditionToPoolWouldExceedPoolCap", inputs: [] },
    { type: "error", name: "AddressAlreadySet", inputs: [] },
    { type: "error", name: "AllowanceDecreasedBelowZero", inputs: [] },
    { type: "error", name: "AlreadyInitialised", inputs: [] },
    { type: "error", name: "ApprovalCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "ApprovalQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "ApproveFromTheZeroAddress", inputs: [] },
    { type: "error", name: "ApproveToTheZeroAddress", inputs: [] },
    { type: "error", name: "AuctionStatusIsNotEnded", inputs: [] },
    { type: "error", name: "AuctionStatusIsNotOpen", inputs: [] },
    {
        type: "error",
        name: "AuxCallFailed",
        inputs: [
            { name: "modules", type: "address[]", internalType: "address[]" },
            { name: "value", type: "uint256", internalType: "uint256" },
            { name: "data", type: "bytes", internalType: "bytes" },
            { name: "txGas", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "BalanceMismatch", inputs: [] },
    { type: "error", name: "BalanceQueryForZeroAddress", inputs: [] },
    { type: "error", name: "BidMustBeBelowTheFloorForRefundDuringAuction", inputs: [] },
    { type: "error", name: "BidMustBeBelowTheFloorWhenReducingQuantity", inputs: [] },
    {
        type: "error",
        name: "BondingCurveError",
        inputs: [{ name: "error", type: "uint8", internalType: "enum IErrors.BondingCurveErrorType" }],
    },
    { type: "error", name: "BurnExceedsBalance", inputs: [] },
    { type: "error", name: "BurnFromTheZeroAddress", inputs: [] },
    { type: "error", name: "CallerIsNotAdminNorFactory", inputs: [] },
    { type: "error", name: "CallerIsNotDepositBoxOwner", inputs: [] },
    { type: "error", name: "CallerIsNotFactory", inputs: [] },
    { type: "error", name: "CallerIsNotFactoryOrProjectOwner", inputs: [] },
    { type: "error", name: "CallerIsNotFactoryProjectOwnerOrPool", inputs: [] },
    {
        type: "error",
        name: "CallerIsNotPlatformAdmin",
        inputs: [{ name: "caller", type: "address", internalType: "address" }],
    },
    {
        type: "error",
        name: "CallerIsNotSuperAdmin",
        inputs: [{ name: "caller", type: "address", internalType: "address" }],
    },
    { type: "error", name: "CallerIsNotTheManager", inputs: [] },
    { type: "error", name: "CallerIsNotTheOwner", inputs: [] },
    { type: "error", name: "CallerMustBeLzApp", inputs: [] },
    { type: "error", name: "CanOnlyReduce", inputs: [] },
    { type: "error", name: "CannotAddLiquidityOnCreateAndUseDRIPool", inputs: [] },
    { type: "error", name: "CannotSetNewManagerToTheZeroAddress", inputs: [] },
    { type: "error", name: "CannotSetNewOwnerToTheZeroAddress", inputs: [] },
    { type: "error", name: "CannotSetToZeroAddress", inputs: [] },
    { type: "error", name: "CannotWithdrawThisToken", inputs: [] },
    { type: "error", name: "CollectionAlreadyRevealed", inputs: [] },
    { type: "error", name: "ContractIsDecommissioned", inputs: [] },
    { type: "error", name: "ContractIsNotPaused", inputs: [] },
    { type: "error", name: "ContractIsPaused", inputs: [] },
    { type: "error", name: "DecreasedAllowanceBelowZero", inputs: [] },
    { type: "error", name: "DeployerOnly", inputs: [] },
    { type: "error", name: "DeploymentError", inputs: [] },
    { type: "error", name: "DepositBoxIsNotOpen", inputs: [] },
    { type: "error", name: "DestinationIsNotTrustedSource", inputs: [] },
    { type: "error", name: "DriPoolAddressCannotBeAddressZero", inputs: [] },
    { type: "error", name: "GasLimitIsTooLow", inputs: [] },
    { type: "error", name: "IncorrectConfirmationValue", inputs: [] },
    { type: "error", name: "IncorrectPayment", inputs: [] },
    { type: "error", name: "InitialLiquidityAlreadyAdded", inputs: [] },
    { type: "error", name: "InitialLiquidityNotYetAdded", inputs: [] },
    { type: "error", name: "InvalidAdapterParams", inputs: [] },
    { type: "error", name: "InvalidAddress", inputs: [] },
    { type: "error", name: "InvalidEndpointCaller", inputs: [] },
    { type: "error", name: "InvalidMinGas", inputs: [] },
    { type: "error", name: "InvalidOracleSignature", inputs: [] },
    { type: "error", name: "InvalidPayload", inputs: [] },
    { type: "error", name: "InvalidReceiver", inputs: [] },
    { type: "error", name: "InvalidSourceSendingContract", inputs: [] },
    { type: "error", name: "InvalidTotalShares", inputs: [] },
    { type: "error", name: "LPLockUpMustFitUint88", inputs: [] },
    { type: "error", name: "LimitsCanOnlyBeRaised", inputs: [] },
    { type: "error", name: "LiquidityPoolCannotBeAddressZero", inputs: [] },
    { type: "error", name: "LiquidityPoolMustBeAContractAddress", inputs: [] },
    { type: "error", name: "ListLengthMismatch", inputs: [] },
    { type: "error", name: "MachineAddressCannotBeAddressZero", inputs: [] },
    { type: "error", name: "ManagerUnauthorizedAccount", inputs: [] },
    { type: "error", name: "MaxBidQuantityIs255", inputs: [] },
    {
        type: "error",
        name: "MaxPublicMintAllowanceExceeded",
        inputs: [
            { name: "requested", type: "uint256", internalType: "uint256" },
            { name: "alreadyMinted", type: "uint256", internalType: "uint256" },
            { name: "maxAllowance", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "MaxSupplyTooHigh", inputs: [] },
    { type: "error", name: "MaxTokensPerTxnExceeded", inputs: [] },
    { type: "error", name: "MaxTokensPerWalletExceeded", inputs: [] },
    { type: "error", name: "MetadataIsLocked", inputs: [] },
    { type: "error", name: "MinGasLimitNotSet", inputs: [] },
    { type: "error", name: "MintERC2309QuantityExceedsLimit", inputs: [] },
    { type: "error", name: "MintToZeroAddress", inputs: [] },
    { type: "error", name: "MintZeroQuantity", inputs: [] },
    { type: "error", name: "MintingIsClosedForever", inputs: [] },
    { type: "error", name: "NewBuyTaxBasisPointsExceedsMaximum", inputs: [] },
    { type: "error", name: "NewSellTaxBasisPointsExceedsMaximum", inputs: [] },
    { type: "error", name: "NoETHForLiquidityPair", inputs: [] },
    { type: "error", name: "NoPaymentDue", inputs: [] },
    { type: "error", name: "NoRefundForCaller", inputs: [] },
    { type: "error", name: "NoStoredMessage", inputs: [] },
    { type: "error", name: "NoTokenForLiquidityPair", inputs: [] },
    { type: "error", name: "NoTrustedPathRecord", inputs: [] },
    { type: "error", name: "NothingToClaim", inputs: [] },
    { type: "error", name: "OperationDidNotSucceed", inputs: [] },
    { type: "error", name: "OracleSignatureHasExpired", inputs: [] },
    { type: "error", name: "OwnerQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "OwnershipNotInitializedForExtraData", inputs: [] },
    { type: "error", name: "ParamTooLargeEndDate", inputs: [] },
    { type: "error", name: "ParamTooLargeMinETH", inputs: [] },
    { type: "error", name: "ParamTooLargePerAddressMax", inputs: [] },
    { type: "error", name: "ParamTooLargePoolPerTxnMinETH", inputs: [] },
    { type: "error", name: "ParamTooLargePoolSupply", inputs: [] },
    { type: "error", name: "ParamTooLargeStartDate", inputs: [] },
    { type: "error", name: "ParamTooLargeVestingDays", inputs: [] },
    { type: "error", name: "ParametersDoNotMatchSignedMessage", inputs: [] },
    { type: "error", name: "PassedConfigDoesNotMatchApproved", inputs: [] },
    { type: "error", name: "PauseCutOffHasPassed", inputs: [] },
    { type: "error", name: "PaymentMustCoverPerMintFee", inputs: [] },
    { type: "error", name: "PermitDidNotSucceed", inputs: [] },
    { type: "error", name: "PlatformAdminCannotBeAddressZero", inputs: [] },
    { type: "error", name: "PlatformTreasuryCannotBeAddressZero", inputs: [] },
    { type: "error", name: "PoolIsAboveMinimum", inputs: [] },
    { type: "error", name: "PoolIsBelowMinimum", inputs: [] },
    { type: "error", name: "PoolPhaseIsClosed", inputs: [] },
    { type: "error", name: "PoolPhaseIsNotAfter", inputs: [] },
    { type: "error", name: "PoolVestingNotYetComplete", inputs: [] },
    { type: "error", name: "ProjectOwnerCannotBeAddressZero", inputs: [] },
    { type: "error", name: "ProofInvalid", inputs: [] },
    { type: "error", name: "QuantityExceedsMaxPossibleCollectionSupply", inputs: [] },
    { type: "error", name: "QuantityExceedsRemainingCollectionSupply", inputs: [] },
    { type: "error", name: "QuantityExceedsRemainingPhaseSupply", inputs: [] },
    { type: "error", name: "ReferralIdAlreadyUsed", inputs: [] },
    { type: "error", name: "RequestingMoreThanAvailableBalance", inputs: [] },
    {
        type: "error",
        name: "RequestingMoreThanRemainingAllocation",
        inputs: [
            { name: "previouslyMinted", type: "uint256", internalType: "uint256" },
            { name: "requested", type: "uint256", internalType: "uint256" },
            { name: "remainingAllocation", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "RoyaltyFeeWillExceedSalePrice", inputs: [] },
    { type: "error", name: "ShareTotalCannotBeZero", inputs: [] },
    { type: "error", name: "SliceOverflow", inputs: [] },
    { type: "error", name: "SuperAdminCannotBeAddressZero", inputs: [] },
    { type: "error", name: "SupplyTotalMismatch", inputs: [] },
    { type: "error", name: "SupportWindowIsNotOpen", inputs: [] },
    { type: "error", name: "TaxFreeAddressCannotBeAddressZero", inputs: [] },
    { type: "error", name: "TaxPeriodStillInForce", inputs: [] },
    { type: "error", name: "TemplateCannotBeAddressZero", inputs: [] },
    { type: "error", name: "TemplateNotFound", inputs: [] },
    { type: "error", name: "ThisMintIsClosed", inputs: [] },
    { type: "error", name: "TotalSharesMustMatchDenominator", inputs: [] },
    { type: "error", name: "TransferAmountExceedsBalance", inputs: [] },
    { type: "error", name: "TransferCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "TransferFromIncorrectOwner", inputs: [] },
    { type: "error", name: "TransferFromZeroAddress", inputs: [] },
    { type: "error", name: "TransferToNonERC721ReceiverImplementer", inputs: [] },
    { type: "error", name: "TransferToZeroAddress", inputs: [] },
    { type: "error", name: "URIQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "UnrecognisedVRFMode", inputs: [] },
    { type: "error", name: "VRFCoordinatorCannotBeAddressZero", inputs: [] },
    { type: "error", name: "ValueExceedsMaximum", inputs: [] },
] as const;
