export const events = [
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { name: "from", type: "address", indexed: true, internalType: "address" },
            { name: "to", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "token", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint160", indexed: false, internalType: "uint160" },
            { name: "expiration", type: "uint48", indexed: false, internalType: "uint48" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Lockdown",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "token", type: "address", indexed: false, internalType: "address" },
            { name: "spender", type: "address", indexed: false, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "NonceInvalidation",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "token", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "newNonce", type: "uint48", indexed: false, internalType: "uint48" },
            { name: "oldNonce", type: "uint48", indexed: false, internalType: "uint48" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Permit",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "token", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint160", indexed: false, internalType: "uint160" },
            { name: "expiration", type: "uint48", indexed: false, internalType: "uint48" },
            { name: "nonce", type: "uint48", indexed: false, internalType: "uint48" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "UnorderedNonceInvalidation",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "word", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "mask", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Subscription",
        inputs: [
            { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "subscriber", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Unsubscription",
        inputs: [
            { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "subscriber", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Donate",
        inputs: [
            { name: "id", type: "bytes32", indexed: true, internalType: "PoolId" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
            { name: "amount0", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "amount1", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Initialize",
        inputs: [
            { name: "id", type: "bytes32", indexed: true, internalType: "PoolId" },
            { name: "currency0", type: "address", indexed: true, internalType: "Currency" },
            { name: "currency1", type: "address", indexed: true, internalType: "Currency" },
            { name: "fee", type: "uint24", indexed: false, internalType: "uint24" },
            { name: "tickSpacing", type: "int24", indexed: false, internalType: "int24" },
            { name: "hooks", type: "address", indexed: false, internalType: "contract IHooks" },
            { name: "sqrtPriceX96", type: "uint160", indexed: false, internalType: "uint160" },
            { name: "tick", type: "int24", indexed: false, internalType: "int24" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ModifyLiquidity",
        inputs: [
            { name: "id", type: "bytes32", indexed: true, internalType: "PoolId" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
            { name: "tickLower", type: "int24", indexed: false, internalType: "int24" },
            { name: "tickUpper", type: "int24", indexed: false, internalType: "int24" },
            { name: "liquidityDelta", type: "int256", indexed: false, internalType: "int256" },
            { name: "salt", type: "bytes32", indexed: false, internalType: "bytes32" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OperatorSet",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "operator", type: "address", indexed: true, internalType: "address" },
            { name: "approved", type: "bool", indexed: false, internalType: "bool" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProtocolFeeControllerUpdated",
        inputs: [{ name: "protocolFeeController", type: "address", indexed: true, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProtocolFeeUpdated",
        inputs: [
            { name: "id", type: "bytes32", indexed: true, internalType: "PoolId" },
            { name: "protocolFee", type: "uint24", indexed: false, internalType: "uint24" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Swap",
        inputs: [
            { name: "id", type: "bytes32", indexed: true, internalType: "PoolId" },
            { name: "sender", type: "address", indexed: true, internalType: "address" },
            { name: "amount0", type: "int128", indexed: false, internalType: "int128" },
            { name: "amount1", type: "int128", indexed: false, internalType: "int128" },
            { name: "sqrtPriceX96", type: "uint160", indexed: false, internalType: "uint160" },
            { name: "liquidity", type: "uint128", indexed: false, internalType: "uint128" },
            { name: "tick", type: "int24", indexed: false, internalType: "int24" },
            { name: "fee", type: "uint24", indexed: false, internalType: "uint24" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { name: "caller", type: "address", indexed: false, internalType: "address" },
            { name: "from", type: "address", indexed: true, internalType: "address" },
            { name: "to", type: "address", indexed: true, internalType: "address" },
            { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { name: "user", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ApprovalForAll",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "operator", type: "address", indexed: true, internalType: "address" },
            { name: "approved", type: "bool", indexed: false, internalType: "bool" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { name: "from", type: "address", indexed: true, internalType: "address" },
            { name: "to", type: "address", indexed: true, internalType: "address" },
            { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "GasSet",
        inputs: [
            { name: "domain", type: "uint32", indexed: false, internalType: "uint32" },
            { name: "gas", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "HookSet",
        inputs: [{ name: "_hook", type: "address", indexed: false, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Initialized",
        inputs: [{ name: "version", type: "uint8", indexed: false, internalType: "uint8" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "IsmSet",
        inputs: [{ name: "_ism", type: "address", indexed: false, internalType: "address" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ReceivedTransferRemote",
        inputs: [
            { name: "origin", type: "uint32", indexed: true, internalType: "uint32" },
            { name: "recipient", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SentTransferRemote",
        inputs: [
            { name: "destination", type: "uint32", indexed: true, internalType: "uint32" },
            { name: "recipient", type: "bytes32", indexed: true, internalType: "bytes32" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RelayedMessage",
        inputs: [
            { name: "source", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "messageNonce", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "messageHash", type: "bytes32", indexed: true, internalType: "bytes32" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SentMessage",
        inputs: [
            { name: "destination", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "target", type: "address", indexed: true, internalType: "address" },
            { name: "messageNonce", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "sender", type: "address", indexed: false, internalType: "address" },
            { name: "message", type: "bytes", indexed: false, internalType: "bytes" },
        ],
        anonymous: false,
    },
] as const;
