/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SmartaccountImport } from './routes/smartaccount'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SmartaccountRoute = SmartaccountImport.update({
  id: '/smartaccount',
  path: '/smartaccount',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/smartaccount': {
      id: '/smartaccount'
      path: '/smartaccount'
      fullPath: '/smartaccount'
      preLoaderRoute: typeof SmartaccountImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/smartaccount': typeof SmartaccountRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/smartaccount': typeof SmartaccountRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/smartaccount': typeof SmartaccountRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/smartaccount'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/smartaccount'
  id: '__root__' | '/' | '/smartaccount'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SmartaccountRoute: typeof SmartaccountRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SmartaccountRoute: SmartaccountRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/smartaccount"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/smartaccount": {
      "filePath": "smartaccount.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
