/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecoveryImport } from './routes/recovery'
import { Route as EmbedImport } from './routes/embed'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RecoveryRoute = RecoveryImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRoute,
} as any)

const EmbedRoute = EmbedImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedImport
      parentRoute: typeof rootRoute
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/recovery': typeof RecoveryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/recovery': typeof RecoveryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/recovery': typeof RecoveryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed' | '/recovery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed' | '/recovery'
  id: '__root__' | '/' | '/embed' | '/recovery'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  RecoveryRoute: typeof RecoveryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  RecoveryRoute: RecoveryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/embed",
        "/recovery"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/embed": {
      "filePath": "embed.tsx"
    },
    "/recovery": {
      "filePath": "recovery.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
