[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "artifacts/" },
]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = true

[rpc_endpoints]
# Local Supersim
localhost = "http://127.0.0.1:8547"
OPChainA = "http://127.0.0.1:9545"
OPChainB = "http://127.0.0.1:9546"
# Live chains
# mainnet = "https://lb.drpc.org/ogrpc?network=mainnet&dkey=${DRPC_API_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://lb.drpc.org/ogrpc?network=sepolia&dkey=${DRPC_API_KEY}"
polygon = "https://lb.drpc.org/ogrpc?network=polygon&dkey=${DRPC_API_KEY}"
arbitrum = "https://lb.drpc.org/ogrpc?network=arbitrum&dkey=${DRPC_API_KEY}"
arbitrum-nova = "https://lb.drpc.org/ogrpc?network=arbitrum-nova&dkey=${DRPC_API_KEY}"
arbitrum-sepolia = "https://lb.drpc.org/ogrpc?network=arbitrum-sepolia&dkey=${DRPC_API_KEY}"
avalanche = "https://lb.drpc.org/ogrpc?network=avalanche&dkey=${DRPC_API_KEY}"
optimism = "https://lb.drpc.org/ogrpc?network=optimism&dkey=${DRPC_API_KEY}"
# optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism-sepolia = "https://lb.drpc.org/ogrpc?network=optimism-sepolia&dkey=${DRPC_API_KEY}"
# bsc = "https://lb.drpc.org/ogrpc?network=bsc&dkey=${DRPC_API_KEY}"
bsc = "https://bsc-dataseed1.defibit.io"
# base = "https://lb.drpc.org/ogrpc?network=base&dkey=${DRPC_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base-sepolia = "https://lb.drpc.org/ogrpc?network=base-sepolia&dkey=${DRPC_API_KEY}"
# base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# unichain = "https://lb.drpc.org/ogrpc?network=unichain&dkey=${DRPC_API_KEY}"
unichain = "https://unichain-rpc.publicnode.com"
# unichain-sepolia = "https://lb.drpc.org/ogrpc?network=unichain-sepolia&dkey=${DRPC_API_KEY}"
unichain-sepolia = "https://unichain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
zircuit = "https://lb.drpc.org/ogrpc?network=zircuit-mainnet&dkey=${DRPC_API_KEY}"
zircuit-testnet = "https://lb.drpc.org/ogrpc?network=zircuit-testnet&dkey=${DRPC_API_KEY}"
ink = "https://lb.drpc.org/ogrpc?network=ink&dkey=${DRPC_API_KEY}"
# ink-sepolia = "https://lb.drpc.org/ogrpc?network=ink-sepolia&dkey=${DRPC_API_KEY}"
ink-sepolia = "https://ink-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
op-interop-0 = "https://interop-alpha-0.optimism.io"
op-interop-1 = "https://interop-alpha-1.optimism.io"
# superseed = "https://lb.drpc.org/ogrpc?network=superseed&dkey=${DRPC_API_KEY}"
superseed = "https://superseed-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
story = "https://mainnet.storyrpc.io"
story-aenid = "https://aeneid.storyrpc.io"
somnia-testnet = "https://dream-rpc.somnia.network"
rari-testnet = "https://testnet.rpc.rarichain.org/http"
appchain-testnet = "https://appchaintestnet.rpc.caldera.xyz/http"

# https://docs.blockscout.com/devs/verification/foundry-verification

[etherscan]
mainnet = { url = "https://api.etherscan.io/v2/api?chainid=1", key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { url = "https://api.etherscan.io/v2/api?chainid=11155111", key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { url = "https://api.etherscan.io/v2/api?chainid=137", key = "${ETHERSCAN_MAINNET_KEY}" }
optimism = { url = "https://api.etherscan.io/v2/api?chainid=10", key = "${ETHERSCAN_MAINNET_KEY}" }
optimism-sepolia = { url = "https://api.etherscan.io/v2/api?chainid=11155420", key = "${ETHERSCAN_MAINNET_KEY}" }
bsc = { url = "https://api.etherscan.io/v2/api?chainid=56", key = "${ETHERSCAN_MAINNET_KEY}" }
base = { url = "https://api.etherscan.io/v2/api?chainid=8453", key = "${ETHERSCAN_MAINNET_KEY}" }
base-sepolia = { url = "https://api.etherscan.io/v2/api?chainid=84532", key = "${ETHERSCAN_MAINNET_KEY}" }
unichain = { url = "https://api.etherscan.io/v2/api?chainid=130", key = "${ETHERSCAN_MAINNET_KEY}" }
unichain-sepolia = { url = "https://api.etherscan.io/v2/api?chainid=1301", key = "${ETHERSCAN_MAINNET_KEY}" }
arbitrum = { url = "https://api.etherscan.io/v2/api?chainid=42161", key = "${ETHERSCAN_MAINNET_KEY}" }
arbitrum-nova = { url = "https://api.etherscan.io/v2/api?chainid=42170", key = "${ETHERSCAN_MAINNET_KEY}" }
arbitrum-sepolia = { url = "https://api.etherscan.io/v2/api?chainid=421614", key = "${ETHERSCAN_MAINNET_KEY}" }
avalanche = { url = "https://api.etherscan.io/v2/api?chainid=43114", key = "${ETHERSCAN_MAINNET_KEY}" }
superseed = { url = "https://explorer-superseed-mainnet-0.t.conduit.xyz/api/", key = "", verifier = "blockscout", chain = "5330" }
op-interop-0 = { url = "https://optimism-interop-alpha-0.blockscout.com/api/", key = "", verifier = "blockscout", chain = "420120000" }
op-interop-1 = { url = "https://optimism-interop-alpha-1.blockscout.com/api/", key = "", verifier = "blockscout", chain = "420120001" }
#zircuit = { url = "https://explorer.zircuit.com" }
#zircuit-testnet = { url = "https://explorer.testnet.zircuit.com" }
#ink = { url = "https://explorer.inkonchain.com" }
#ink-sepolia = { url = "https://explorer-sepolia.inkonchain.com" }
story = { url = "https://www.storyscan.io/api/", key = "", verifier = "blockscout", chain = "1514" }
#story-aeneid = { url = "https://storyscan.xyz" }
#somnia-testnet = { url = "https://shannon-explorer.somnia.network" }
#taraxa = { url = "https://mainnet.explorer.taraxa.io" }
#taraxa-testnet = { url = "https://testnet.explorer.taraxa.io" }
# rari-testnet = { url = "https://explorer.rarichain.org/api/", key = "", verifier = "blockscout", chain = "1918988905" }
appchain-testnet = { url = "https://appchaintestnet.explorer.caldera.xyz/api/", key = "", verifier = "blockscout", chain = "4661" }

#### FAUCETS ###
# ink => superchain console
# https://metaverse-browser.somnia.network/faucet
# hedera evm TODO
# https://testnets.superbridge.app/ => unichain, base
# https://superbridge.app/

# ink

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
