[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
op-interop-0 = "https://interop-alpha-0.optimism.io"
op-interop-1 = "https://interop-alpha-1.optimism.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
