/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as IndexImport } from './routes/index'
import { Route as BasketBasketIdImport } from './routes/basket/$basketId'

// Create/Update Routes

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BasketBasketIdRoute = BasketBasketIdImport.update({
  id: '/basket/$basketId',
  path: '/basket/$basketId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/basket/$basketId': {
      id: '/basket/$basketId'
      path: '/basket/$basketId'
      fullPath: '/basket/$basketId'
      preLoaderRoute: typeof BasketBasketIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/basket/$basketId': typeof BasketBasketIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/basket/$basketId': typeof BasketBasketIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/basket/$basketId': typeof BasketBasketIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portfolio' | '/basket/$basketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portfolio' | '/basket/$basketId'
  id: '__root__' | '/' | '/portfolio' | '/basket/$basketId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  BasketBasketIdRoute: typeof BasketBasketIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  BasketBasketIdRoute: BasketBasketIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/portfolio",
        "/basket/$basketId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/basket/$basketId": {
      "filePath": "basket/$basketId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
